# Generated by Django 3.1.1 on 2020-09-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default='default image', upload_to='images/'),
        ),
    ]
